version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  sqlserver:
    container_name: sqlserver.db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - '1433:1433'
    volumes:
      - sqlserver-data:/var/lib/sqlserver/data
    networks:
      - tedu_ecommerce
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin@123
networks:
  tedu_ecommerce:
    driver: bridge
volumes:
  redis-data:
  sqlserver-data: